export TW_DEVICE_VERSION=R11_1
export OF_TARGET_DEVICES="X00QD"
export TARGET_DEVICE_ALT="x00qd, ASUS_X00QD, x00q, X00Q"
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export FOX_DISABLE_APP_MANAGER=1
export OF_USE_LOCKSCREEN_BUTTON=1
export OF_MAINTAINER="MLZ94"
export FOX_R11=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1
export FOX_USE_NANO_EDITOR=1
export OF_SCREEN_H=2246
export OF_STATUS_H=90
export OF_STATUS_INDENT_LEFT=57
export OF_STATUS_INDENT_RIGHT=57
add_lunch_combo omni_X00QD-userdebug
add_lunch_combo omni_X00QD-eng
